version: "3.9"
services:
  api-gateway:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    volumes:
       - ../:/app
       - maven:/root/.m2
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - my-network
    depends_on:
      - jaeger
    
  jaeger:
    image: jaegertracing/all-in-one:1
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - my-network

volumes:
  maven:

networks:
  my-network: