version: "3.9"
services:
  api-gateway:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    volumes:
       - ../:/app
       - maven:/root/.m2
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - my-network
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/notificator
    
  postgres:
    image: postgres:bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: notificator
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - my-network
      - intern

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - postgres
    networks:
      - intern

volumes:
  maven:
  db-data:

networks:
  my-network:
  intern: