name: build

on: 
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
      ref:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04

    outputs:
      version: ${{ steps.project.outputs.version }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.sha }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: 'maven'

      - name: Bump Version
        id: bump
        uses: nnichols/maven-version-bump-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build native executable
        run: ./mvnw package -Pnative -DskipTests -Dquarkus.native.container-build=true

      - name: Extract Maven project version
        run: echo "version=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
        id: project

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: api-gateway-${{ steps.project.outputs.version }}
          path: target/api-gateway-${{ steps.project.outputs.version }}-runner
          retention-days: 5

  publish:
    needs: build
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      sha: ${{ github.sha }}
      ref: ${{ github.ref }}
      version: ${{ needs.build.outputs.version }}
      run_id: ${{ github.run_id }}