name: build

on: 
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
      ref:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.sha }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: 'maven'

      - name: Set version
        run: ./mvnw versions:set -DnewVersion="${{ github.event.release.tag_name }}"

      - name: Build native executable
        run: ./mvnw package -Pnative -DskipTests -Dquarkus.native.container-build=true

      - name: Extract Maven project version
        run: echo "version=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_ENV

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: api-gateway-${{ env.version }}
          path: target/api-gateway-${{ env.version }}-runner
          retention-days: 5

      # - name: Trigger next workflow
      #   if: success()
      #   uses: peter-evans/repository-dispatch@v1
      #   with:
      #     token: ${{ secrets.REPO_GHA_PAT }}
      #     repository: ${{ github.repository }}
      #     event-type: trigger-docker
      #     client-payload: '{"ref": "${{ github.event.client_payload.ref }}", "sha": "${{ github.event.client_payload.sha }}", "version": "${{ steps.project.outputs.version }}", "run_id": "${{ github.run_id }}"}'

  publish:
    needs: build
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      sha: ${{ github.sha }}
      ref: ${{ github.ref }}
      version: ${{ env.version }}
      run_id: ${{ github.run_id }}