name: build

on: 
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-20.04

    outputs:
      version: ${{ steps.bump.outputs.version }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          # cache: 'maven'

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Bump Version
        id: bump
        uses: nnichols/maven-version-bump-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build native executable
        run: ./mvnw package -Pnative -DskipTests -Dquarkus.native.container-build=true

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: api-gateway-${{ steps.bump.outputs.version }}
          path: target/api-gateway-${{ steps.bump.outputs.version }}-runner
          retention-days: 5

  publish:
    needs: build
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      version: ${{ needs.build.outputs.version }}