name: publish

on: 
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
      ref:
        required: true
        type: string
      version:
        required: true
        type: string
      run_id:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.sha }}

      - name: Download artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: api-gateway-${{ inputs.version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: src/main/docker/Dockerfile.native-micro
          platforms: linux/amd64
          push: true
          tags: |
            benevolentalien/api-gateway:latest
            benevolentalien/api-gateway:${{ inputs.version }}