name: publish-docker

on:
  repository_dispatch:
    types: [trigger-docker]

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    env:
      OS: linux
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.sha }}

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.client_payload.run_id }}
          name: api-gateway-${{ github.event.client_payload.version }}
          path: target
          if_no_artifact_found: fail

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: src/main/docker/Dockerfile.native-micro
          platforms: linux/amd64
          push: true
          tags: |
            benevolent-alien/api-gateway:latest
            benevolent-alien/api-gateway:${{ github.event.client_payload.version }}